---
- name: get consul
  unarchive: src="{{consul_url}}" dest=/usr/bin owner=root group=root mode=0755 remote_src=yes

- name: copy consul-alerts
  copy: src="consul-alerts" dest=/usr/bin owner=root group=root mode=0755
