---
- name: define app name
  set_fact: app_name="etcd"
  tags: ['deploy_etcd_server']

- name: define version
  set_fact:
     app_conf: "/etc/{{app_name}}"
     app_data: "/var/{{app_name}}"
  tags: ['deploy_etcd_server']

- name: prepare directories
  file: path="{{item}}" state=directory
  with_items:
    - "{{app_conf}}"
    - "{{app_data}}"
  tags: ['deploy_etcd_server']

- name: get etcd
  unarchive: src="{{etcd_url}}" dest=/tmp remote_src=yes
  tags: ['deploy_etcd_server']

- name: move binaries
  copy: src="{{item.file}}" dest="{{item.path}}" remote_src=yes mode=0755
  with_items:
    - { file: "/tmp/etcd-v{{etcd_ver}}-linux-amd64/etcd", path: "/usr/bin" }
    - { file: "/tmp/etcd-v{{etcd_ver}}-linux-amd64/etcdctl", path: "/usr/bin" }
  tags: ['deploy_etcd_server']

- name: remove download
  file: path="{{item}}" state=absent
  with_items:
    - "/tmp/etcd-v{{etcd_ver}}-linux-amd64"
    - "/tmp/etcd-v{{etcd_ver}}-linux-amd64.tar.gz"
  tags: ['deploy_etcd_server']

- name: define hosts in string for templating
  set_fact: >
    etcd_hosts="{% for h in play_hosts %}{{h}}=http://{{hostvars[h].privip}}:2380,{% endfor %}"
  tags: ['deploy_etcd_server']

- name: template etcd config files
  template: src="{{item.file}}" dest="{{item.path}}"
  with_items:
    - { file: "etcd.conf", path: "{{app_conf}}" }
    - { file: "consul.service", path: "{{app_conf}}" }
    - { file: "etcd.service", path: "/lib/systemd/system" }
  tags: ['deploy_etcd_server']

- name: update systemd conf and run etcd
  systemd: name=etcd state=restarted daemon_reload=yes enabled=yes
  tags: ['deploy_etcd_server']

- name: wait for etcd to come up
  wait_for: host="etcd.service" port="2379" timeout=900
  tags: ['deploy_etcd_server']

- name: fill in etcd flannel config
  run_once: yes
  command: >
    curl -L -X PUT http://etcd:2379/v2/keys/coreos.com/network/config -d value='{"Network": "18.18.0.0/8", "Backend": { "Type": "vxlan" }}'
  tags: ['deploy_etcd_server']
